USE [ERP_Mercury]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_OrderDiscountType](
	[DISCOUNTTYPE_ID] [dbo].[D_ID] NOT NULL,
	[DISCOUNTTYPE_NAME] [dbo].[D_NAME] NOT NULL,
 CONSTRAINT [PK_T_CSMDISCOUNTTYPE] PRIMARY KEY CLUSTERED 
(
	[DISCOUNTTYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 0, 'Скидка ретро' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 1, 'Скидка фиксированная' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 2, 'Скидка за оборудование' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 3, 'Скидка промо' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 4, 'Скидка по спеццене' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 5, 'Скидка по акции' )

INSERT INTO T_OrderDiscountType( DISCOUNTTYPE_ID, DISCOUNTTYPE_NAME )
VALUES( 6, 'Скидка за предоплату' )
GO