/*------   ------*/

SET TERM ~~~ ;
 create procedure USP_GETWAYBILLINFO_BYID_FROMSQL (
    IN_WAYBILL_ID integer)
returns (
    WAYBILL_ID integer,
    STOCK_ID integer,
    CUSTOMER_ID integer,
    DEPART_CODE char(3),
    WAYBILL_SRCCODE integer,
    WAYBILL_SRCDOC varchar(16),
    WAYBILL_SRCID integer,
    WAYBILL_SRCDATE date,
    WAYBILL_BEGINDATE date,
    WAYBILL_ALLPRICE double precision,
    WAYBILL_RETALLPRICE double precision,
    WAYBILL_ENDDATE date,
    CURRENCY_CODE char(3),
    WAYBILL_CURRENCYRATE double precision,
    WAYBILL_AMOUNTPAID double precision,
    WAYBILL_DATELASTPAID date,
    WAYBILL_SHIPDATE date,
    WAYBILL_SHIPPED integer,
    WAYBILL_NUM varchar(16),
    WAYBILL_ALLDISCOUNT double precision,
    WAYBILL_TOTALPRICE double precision,
    WAYBILL_SALDO double precision,
    WAYBILL_CURRENCYALLPRICE double precision,
    WAYBILL_CURRENCYRETALLPRICE double precision,
    WAYBILL_CURRENCYAMOUNTPAID double precision,
    WAYBILL_CURRENCYALLDISCOUNT double precision,
    WAYBILL_CURRENCYTOTALPRICE double precision,
    WAYBILL_CURRENCYSALDO double precision,
    CHILDCUST_ID integer,
    WAYBILL_SHIPMODE integer,
    WAYBILL_INCASSO integer,
    WAYBILL_BONUS integer,
    COMPANY_ID integer,
    WAYBILL_OPERDATE date,
    WAYBILL_EXPORTMODE integer,
    WAYBILL_REPRESENTATIVE varchar(48),
    WAYBILL_RETURN integer,
    WAYBILL_SEND integer,
    WAYBILL_USDRATE double precision,
    WAYBILL_MONEYBONUS integer,
    WAYBILL_CURRENCYMAINRATE double precision,
    WAYBILL_FORSTOCK integer,
    WAYBILL_DELIVERYADDRESS varchar(128),
    WAYBILL_DELIVERYDATE date,
    WAYBILL_AUTOCREATED integer,
    WAYBILL_DRIVER varchar(128),
    WAYBILL_VEHICLE varchar(128),
    WAYBILL_CARRIER varchar(128),
    WAYBILL_ROUTESHEET varchar(128),
    ROUTESHEET_GUID varchar(36),
    WAYBILL_EXCLUDEFROM_ADJ integer,
    WAYBILL_CALCSALDO double precision,
    WAYBILL_CURRENCYCALCSALDO double precision,
    ERROR_NUMBER integer,
    ERROR_TEXT varchar(480))
as
BEGIN

  ERROR_NUMBER = -1;
  ERROR_TEXT = '';

  SELECT WAYBILL_ID, STOCK_ID, CUSTOMER_ID, DEPART_CODE, WAYBILL_SRCCODE, WAYBILL_SRCDOC,
    WAYBILL_SRCID, WAYBILL_SRCDATE, WAYBILL_BEGINDATE, WAYBILL_ALLPRICE, WAYBILL_RETALLPRICE,
    WAYBILL_ENDDATE, CURRENCY_CODE, WAYBILL_CURRENCYRATE, WAYBILL_AMOUNTPAID, WAYBILL_DATELASTPAID,
    WAYBILL_SHIPDATE, WAYBILL_SHIPPED, WAYBILL_NUM, WAYBILL_ALLDISCOUNT, WAYBILL_TOTALPRICE,
    WAYBILL_SALDO, WAYBILL_CURRENCYALLPRICE, WAYBILL_CURRENCYRETALLPRICE, WAYBILL_CURRENCYAMOUNTPAID,
    WAYBILL_CURRENCYALLDISCOUNT, WAYBILL_CURRENCYTOTALPRICE, WAYBILL_CURRENCYSALDO,
    CHILDCUST_ID, WAYBILL_SHIPMODE, WAYBILL_INCASSO, WAYBILL_BONUS, COMPANY_ID,
    WAYBILL_OPERDATE, WAYBILL_EXPORTMODE, WAYBILL_REPRESENTATIVE, WAYBILL_RETURN,
    WAYBILL_SEND, WAYBILL_USDRATE, WAYBILL_MONEYBONUS, WAYBILL_CURRENCYMAINRATE,
    WAYBILL_FORSTOCK, WAYBILL_DELIVERYADDRESS, WAYBILL_DELIVERYDATE, WAYBILL_AUTOCREATED,
    WAYBILL_DRIVER, WAYBILL_VEHICLE, WAYBILL_CARRIER, WAYBILL_ROUTESHEET,
    ROUTESHEET_GUID, WAYBILL_EXCLUDEFROM_ADJ, WAYBILL_CALCSALDO, WAYBILL_CURRENCYCALCSALDO
  FROM t_waybill
  WHERE WAYBILL_ID = :IN_WAYBILL_ID
  into :WAYBILL_ID, :STOCK_ID, :CUSTOMER_ID, :DEPART_CODE, :WAYBILL_SRCCODE, :WAYBILL_SRCDOC,
    :WAYBILL_SRCID, :WAYBILL_SRCDATE, :WAYBILL_BEGINDATE, :WAYBILL_ALLPRICE, :WAYBILL_RETALLPRICE,
    :WAYBILL_ENDDATE, :CURRENCY_CODE, :WAYBILL_CURRENCYRATE, :WAYBILL_AMOUNTPAID, :WAYBILL_DATELASTPAID,
    :WAYBILL_SHIPDATE, :WAYBILL_SHIPPED, :WAYBILL_NUM, :WAYBILL_ALLDISCOUNT, :WAYBILL_TOTALPRICE,
    :WAYBILL_SALDO, :WAYBILL_CURRENCYALLPRICE, :WAYBILL_CURRENCYRETALLPRICE, :WAYBILL_CURRENCYAMOUNTPAID,
    :WAYBILL_CURRENCYALLDISCOUNT, :WAYBILL_CURRENCYTOTALPRICE, :WAYBILL_CURRENCYSALDO,
    :CHILDCUST_ID, :WAYBILL_SHIPMODE, :WAYBILL_INCASSO, :WAYBILL_BONUS, :COMPANY_ID,
    :WAYBILL_OPERDATE, :WAYBILL_EXPORTMODE, :WAYBILL_REPRESENTATIVE, :WAYBILL_RETURN,
    :WAYBILL_SEND, :WAYBILL_USDRATE, :WAYBILL_MONEYBONUS, :WAYBILL_CURRENCYMAINRATE,
    :WAYBILL_FORSTOCK, :WAYBILL_DELIVERYADDRESS, :WAYBILL_DELIVERYDATE, :WAYBILL_AUTOCREATED,
    :WAYBILL_DRIVER, :WAYBILL_VEHICLE, :WAYBILL_CARRIER, :WAYBILL_ROUTESHEET,
    :ROUTESHEET_GUID, :WAYBILL_EXCLUDEFROM_ADJ, :WAYBILL_CALCSALDO, :WAYBILL_CURRENCYCALCSALDO;

  ERROR_NUMBER = 0;
  ERROR_TEXT = cast(('Успешное завершение операции. УИ накладной: ' || cast( :IN_WAYBILL_ID as varchar(16))) as varchar(480));

  suspend;
  exit;

  when any do
  begin
    ERROR_NUMBER = -1;
    ERROR_TEXT = cast((:ERROR_TEXT || ' Не удалось полчуит информацию о накладной. Неизвестная ошибка, обратитесь к разработчикам.') as varchar(480));
    suspend;
  end

END
 ~~~
SET TERM ; ~~~
commit work;

/*------   ------*/

SET TERM ~~~ ;
 create procedure USP_GETWAYBITMSINFO_BYID_FROMSQL (
    IN_WAYBILL_ID integer,
    ERROR_NUMBER integer,
    ERROR_TEXT varchar(480))
returns (
    WAYBITMS_ID integer,
    WAYBILL_ID integer,
    PARTS_ID integer,
    MEASURE_ID integer,
    WAYBITMS_QUANTITY integer,
    WAYBITMS_PACKID integer,
    WAYBITMS_PRICE double precision,
    WAYBITMS_DATELASTPAID date,
    WAYBITMS_AMOUNTPAID double precision,
    WAYBITMS_BASEPRICE double precision,
    WAYBITMS_MARKUP double precision,
    WAYBITMS_DISCOUNT double precision,
    WAYBITMS_RETQTY integer,
    WAYBITMS_ALLPRICE double precision,
    WAYBITMS_DISCOUNTPRICE double precision,
    WAYBITMS_TOTALPRICE double precision,
    WAYBITMS_LEAVQTY integer,
    WAYBITMS_LEAVTOTALPRICE double precision,
    WAYBITMS_CURRENCYPRICE double precision,
    WAYBITMS_CURRENCYAMOUNTPAID double precision,
    WAYBITMS_CURRENCYALLPRICE double precision,
    WAYBITMS_CURRENCYDISCOUNTPRICE double precision,
    WAYBITMS_CURRENCYTOTALPRICE double precision,
    WAYBITMS_CURRENCYLEAVTOTALPRICE double precision,
    WAYBITMS_NDS double precision,
    WAYBITMS_DISCOUNTFROMPRICE double precision,
    SPLITMS_ID integer)
as
BEGIN

  ERROR_NUMBER = -1;
  ERROR_TEXT = '';

  SELECT WAYBITMS_ID, WAYBILL_ID, PARTS_ID, MEASURE_ID, WAYBITMS_QUANTITY,
    WAYBITMS_PACKID, WAYBITMS_PRICE, WAYBITMS_DATELASTPAID, WAYBITMS_AMOUNTPAID,
    WAYBITMS_BASEPRICE, WAYBITMS_MARKUP, WAYBITMS_DISCOUNT, WAYBITMS_RETQTY,
    WAYBITMS_ALLPRICE, WAYBITMS_DISCOUNTPRICE, WAYBITMS_TOTALPRICE, WAYBITMS_LEAVQTY,
    WAYBITMS_LEAVTOTALPRICE, WAYBITMS_CURRENCYPRICE, WAYBITMS_CURRENCYAMOUNTPAID,
    WAYBITMS_CURRENCYALLPRICE, WAYBITMS_CURRENCYDISCOUNTPRICE, WAYBITMS_CURRENCYTOTALPRICE,
    WAYBITMS_CURRENCYLEAVTOTALPRICE, WAYBITMS_NDS, WAYBITMS_DISCOUNTFROMPRICE, SPLITMS_ID
  FROM t_waybitms waybitms
  WHERE waybitms.waybill_id = :IN_WAYBILL_ID
  into :WAYBITMS_ID, :WAYBILL_ID, :PARTS_ID, :MEASURE_ID, :WAYBITMS_QUANTITY,
    :WAYBITMS_PACKID, :WAYBITMS_PRICE, :WAYBITMS_DATELASTPAID, :WAYBITMS_AMOUNTPAID,
    :WAYBITMS_BASEPRICE, :WAYBITMS_MARKUP, :WAYBITMS_DISCOUNT, :WAYBITMS_RETQTY,
    :WAYBITMS_ALLPRICE, :WAYBITMS_DISCOUNTPRICE, :WAYBITMS_TOTALPRICE, :WAYBITMS_LEAVQTY,
    :WAYBITMS_LEAVTOTALPRICE, :WAYBITMS_CURRENCYPRICE, :WAYBITMS_CURRENCYAMOUNTPAID,
    :WAYBITMS_CURRENCYALLPRICE, :WAYBITMS_CURRENCYDISCOUNTPRICE, :WAYBITMS_CURRENCYTOTALPRICE,
    :WAYBITMS_CURRENCYLEAVTOTALPRICE, :WAYBITMS_NDS, :WAYBITMS_DISCOUNTFROMPRICE, :SPLITMS_ID;

  ERROR_NUMBER = 0;
  ERROR_TEXT = cast(('Успешное завершение операции. УИ накладной: ' || cast( :IN_WAYBILL_ID as varchar(16))) as varchar(480));

  suspend;
  exit;

  when any do
  begin
    ERROR_NUMBER = -1;
    ERROR_TEXT = cast((:ERROR_TEXT || ' Не удалось полчуит информацию о накладной. Неизвестная ошибка, обратитесь к разработчикам.') as varchar(480));
    suspend;
  end


END
 ~~~
SET TERM ; ~~~
commit work;

/*------   ------*/

SET TERM ~~~ ;
 create procedure USP_GETWAYBILLINFO_BYPERIOD_FROMSQL (
    PERIOD_BEGIN_DATE date,
    PERIOD_END_DATE date)
returns (
    WAYBILL_ID integer,
    STOCK_ID integer,
    CUSTOMER_ID integer,
    DEPART_CODE char(3),
    WAYBILL_SRCCODE integer,
    WAYBILL_SRCDOC varchar(16),
    WAYBILL_SRCID integer,
    WAYBILL_SRCDATE date,
    WAYBILL_BEGINDATE date,
    WAYBILL_ALLPRICE double precision,
    WAYBILL_RETALLPRICE double precision,
    WAYBILL_ENDDATE date,
    CURRENCY_CODE char(3),
    WAYBILL_CURRENCYRATE double precision,
    WAYBILL_AMOUNTPAID double precision,
    WAYBILL_DATELASTPAID date,
    WAYBILL_SHIPDATE date,
    WAYBILL_SHIPPED integer,
    WAYBILL_NUM varchar(16),
    WAYBILL_ALLDISCOUNT double precision,
    WAYBILL_TOTALPRICE double precision,
    WAYBILL_SALDO double precision,
    WAYBILL_CURRENCYALLPRICE double precision,
    WAYBILL_CURRENCYRETALLPRICE double precision,
    WAYBILL_CURRENCYAMOUNTPAID double precision,
    WAYBILL_CURRENCYALLDISCOUNT double precision,
    WAYBILL_CURRENCYTOTALPRICE double precision,
    WAYBILL_CURRENCYSALDO double precision,
    CHILDCUST_ID integer,
    WAYBILL_SHIPMODE integer,
    WAYBILL_INCASSO integer,
    WAYBILL_BONUS integer,
    COMPANY_ID integer,
    WAYBILL_OPERDATE date,
    WAYBILL_EXPORTMODE integer,
    WAYBILL_REPRESENTATIVE varchar(48),
    WAYBILL_RETURN integer,
    WAYBILL_SEND integer,
    WAYBILL_USDRATE double precision,
    WAYBILL_MONEYBONUS integer,
    WAYBILL_CURRENCYMAINRATE double precision,
    WAYBILL_FORSTOCK integer,
    WAYBILL_DELIVERYADDRESS varchar(128),
    WAYBILL_DELIVERYDATE date,
    WAYBILL_AUTOCREATED integer,
    WAYBILL_DRIVER varchar(128),
    WAYBILL_VEHICLE varchar(128),
    WAYBILL_CARRIER varchar(128),
    WAYBILL_ROUTESHEET varchar(128),
    ROUTESHEET_GUID varchar(36),
    WAYBILL_EXCLUDEFROM_ADJ integer,
    WAYBILL_CALCSALDO double precision,
    WAYBILL_CURRENCYCALCSALDO double precision)
as
BEGIN

  FOR SELECT WAYBILL_ID, STOCK_ID, CUSTOMER_ID, DEPART_CODE, WAYBILL_SRCCODE, WAYBILL_SRCDOC,
    WAYBILL_SRCID, WAYBILL_SRCDATE, WAYBILL_BEGINDATE, WAYBILL_ALLPRICE, WAYBILL_RETALLPRICE,
    WAYBILL_ENDDATE, CURRENCY_CODE, WAYBILL_CURRENCYRATE, WAYBILL_AMOUNTPAID, WAYBILL_DATELASTPAID,
    WAYBILL_SHIPDATE, WAYBILL_SHIPPED, WAYBILL_NUM, WAYBILL_ALLDISCOUNT, WAYBILL_TOTALPRICE,
    WAYBILL_SALDO, WAYBILL_CURRENCYALLPRICE, WAYBILL_CURRENCYRETALLPRICE, WAYBILL_CURRENCYAMOUNTPAID,
    WAYBILL_CURRENCYALLDISCOUNT, WAYBILL_CURRENCYTOTALPRICE, WAYBILL_CURRENCYSALDO,
    CHILDCUST_ID, WAYBILL_SHIPMODE, WAYBILL_INCASSO, WAYBILL_BONUS, COMPANY_ID,
    WAYBILL_OPERDATE, WAYBILL_EXPORTMODE, WAYBILL_REPRESENTATIVE, WAYBILL_RETURN,
    WAYBILL_SEND, WAYBILL_USDRATE, WAYBILL_MONEYBONUS, WAYBILL_CURRENCYMAINRATE,
    WAYBILL_FORSTOCK, WAYBILL_DELIVERYADDRESS, WAYBILL_DELIVERYDATE, WAYBILL_AUTOCREATED,
    WAYBILL_DRIVER, WAYBILL_VEHICLE, WAYBILL_CARRIER, WAYBILL_ROUTESHEET,
    ROUTESHEET_GUID, WAYBILL_EXCLUDEFROM_ADJ, WAYBILL_CALCSALDO, WAYBILL_CURRENCYCALCSALDO
  FROM t_waybill
  WHERE WAYBILL_BEGINDATE BETWEEN :PERIOD_BEGIN_DATE AND :PERIOD_END_DATE
  into :WAYBILL_ID, :STOCK_ID, :CUSTOMER_ID, :DEPART_CODE, :WAYBILL_SRCCODE, :WAYBILL_SRCDOC,
    :WAYBILL_SRCID, :WAYBILL_SRCDATE, :WAYBILL_BEGINDATE, :WAYBILL_ALLPRICE, :WAYBILL_RETALLPRICE,
    :WAYBILL_ENDDATE, :CURRENCY_CODE, :WAYBILL_CURRENCYRATE, :WAYBILL_AMOUNTPAID, :WAYBILL_DATELASTPAID,
    :WAYBILL_SHIPDATE, :WAYBILL_SHIPPED, :WAYBILL_NUM, :WAYBILL_ALLDISCOUNT, :WAYBILL_TOTALPRICE,
    :WAYBILL_SALDO, :WAYBILL_CURRENCYALLPRICE, :WAYBILL_CURRENCYRETALLPRICE, :WAYBILL_CURRENCYAMOUNTPAID,
    :WAYBILL_CURRENCYALLDISCOUNT, :WAYBILL_CURRENCYTOTALPRICE, :WAYBILL_CURRENCYSALDO,
    :CHILDCUST_ID, :WAYBILL_SHIPMODE, :WAYBILL_INCASSO, :WAYBILL_BONUS, :COMPANY_ID,
    :WAYBILL_OPERDATE, :WAYBILL_EXPORTMODE, :WAYBILL_REPRESENTATIVE, :WAYBILL_RETURN,
    :WAYBILL_SEND, :WAYBILL_USDRATE, :WAYBILL_MONEYBONUS, :WAYBILL_CURRENCYMAINRATE,
    :WAYBILL_FORSTOCK, :WAYBILL_DELIVERYADDRESS, :WAYBILL_DELIVERYDATE, :WAYBILL_AUTOCREATED,
    :WAYBILL_DRIVER, :WAYBILL_VEHICLE, :WAYBILL_CARRIER, :WAYBILL_ROUTESHEET,
    :ROUTESHEET_GUID, :WAYBILL_EXCLUDEFROM_ADJ, :WAYBILL_CALCSALDO, :WAYBILL_CURRENCYCALCSALDO
  DO
   suspend;

END
 ~~~
SET TERM ; ~~~
commit work;

/*------   ------*/

SET TERM ~~~ ;
create procedure USP_GETWAYBITMSINFO_BYPERIOD_FROMSQL (
    PERIOD_BEGIN_DATE date,
    PERIOD_END_DATE date)
returns (
    WAYBITMS_ID integer,
    WAYBILL_ID integer,
    PARTS_ID integer,
    MEASURE_ID integer,
    WAYBITMS_QUANTITY integer,
    WAYBITMS_PACKID integer,
    WAYBITMS_PRICE double precision,
    WAYBITMS_DATELASTPAID date,
    WAYBITMS_AMOUNTPAID double precision,
    WAYBITMS_BASEPRICE double precision,
    WAYBITMS_MARKUP double precision,
    WAYBITMS_DISCOUNT double precision,
    WAYBITMS_RETQTY integer,
    WAYBITMS_ALLPRICE double precision,
    WAYBITMS_DISCOUNTPRICE double precision,
    WAYBITMS_TOTALPRICE double precision,
    WAYBITMS_LEAVQTY integer,
    WAYBITMS_LEAVTOTALPRICE double precision,
    WAYBITMS_CURRENCYPRICE double precision,
    WAYBITMS_CURRENCYAMOUNTPAID double precision,
    WAYBITMS_CURRENCYALLPRICE double precision,
    WAYBITMS_CURRENCYDISCOUNTPRICE double precision,
    WAYBITMS_CURRENCYTOTALPRICE double precision,
    WAYBITMS_CURRENCYLEAVTOTALPRICE double precision,
    WAYBITMS_NDS double precision,
    WAYBITMS_DISCOUNTFROMPRICE double precision,
    SPLITMS_ID integer)
as
BEGIN

  FOR SELECT WAYBITMS_ID, WAYBILL_ID, PARTS_ID, MEASURE_ID, WAYBITMS_QUANTITY,
    WAYBITMS_PACKID, WAYBITMS_PRICE, WAYBITMS_DATELASTPAID, WAYBITMS_AMOUNTPAID,
    WAYBITMS_BASEPRICE, WAYBITMS_MARKUP, WAYBITMS_DISCOUNT, WAYBITMS_RETQTY,
    WAYBITMS_ALLPRICE, WAYBITMS_DISCOUNTPRICE, WAYBITMS_TOTALPRICE, WAYBITMS_LEAVQTY,
    WAYBITMS_LEAVTOTALPRICE, WAYBITMS_CURRENCYPRICE, WAYBITMS_CURRENCYAMOUNTPAID,
    WAYBITMS_CURRENCYALLPRICE, WAYBITMS_CURRENCYDISCOUNTPRICE, WAYBITMS_CURRENCYTOTALPRICE,
    WAYBITMS_CURRENCYLEAVTOTALPRICE, WAYBITMS_NDS, WAYBITMS_DISCOUNTFROMPRICE, SPLITMS_ID
  FROM t_waybill waybill, t_waybitms waybitms
  WHERE waybill.WAYBILL_BEGINDATE BETWEEN :PERIOD_BEGIN_DATE AND :PERIOD_END_DATE
    and waybill.waybill_id = waybitms.waybill_id
  into :WAYBITMS_ID, :WAYBILL_ID, :PARTS_ID, :MEASURE_ID, :WAYBITMS_QUANTITY,
    :WAYBITMS_PACKID, :WAYBITMS_PRICE, :WAYBITMS_DATELASTPAID, :WAYBITMS_AMOUNTPAID,
    :WAYBITMS_BASEPRICE, :WAYBITMS_MARKUP, :WAYBITMS_DISCOUNT, :WAYBITMS_RETQTY,
    :WAYBITMS_ALLPRICE, :WAYBITMS_DISCOUNTPRICE, :WAYBITMS_TOTALPRICE, :WAYBITMS_LEAVQTY,
    :WAYBITMS_LEAVTOTALPRICE, :WAYBITMS_CURRENCYPRICE, :WAYBITMS_CURRENCYAMOUNTPAID,
    :WAYBITMS_CURRENCYALLPRICE, :WAYBITMS_CURRENCYDISCOUNTPRICE, :WAYBITMS_CURRENCYTOTALPRICE,
    :WAYBITMS_CURRENCYLEAVTOTALPRICE, :WAYBITMS_NDS, :WAYBITMS_DISCOUNTFROMPRICE, :SPLITMS_ID
  DO
   suspend;

END
 ~~~
SET TERM ; ~~~
commit work;

